# Generated by Django 5.0.4 on 2024-04-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_disponible',
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
