# Generated by Django 5.0.4 on 2024-04-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0002_remove_insumo_cantidad_disponible_insumo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pagado', 'PAGADO'), ('pendiente', 'PENDIENTE'), ('cancelado', 'CANCELADO')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
